### ISSUE TITLE
Error on sudo make install step

### ISSUE THREAD

**Issue by qymspace** [Leosocy/RobustPalmRoi#17]
First thanks for the library. I have been eagerly waiting for it.
Now to my issue, the compilation process is failing at ```sudo make install ``` step 
```
[  8%] Linking CXX shared library librobust-palm-roi.so
/usr/bin/ld: /usr/local/lib/libyaml-cpp.a(exceptions.cpp.o): relocation R_X86_64_32S against `_ZTVN4YAML9ExceptionE' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libyaml-cpp.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
CMakeFiles/robust-palm-roi.dir/build.make:403: recipe for target 'librobust-palm-roi.so.0.1.0' failed
make[2]: *** [librobust-palm-roi.so.0.1.0] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/robust-palm-roi.dir/all' failed
make[1]: *** [CMakeFiles/robust-palm-roi.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by Leosocy** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        You should reinstall yaml-cpp as a shared library. Stepmkdir build; cd buildcmake -DBUILD_SHARED_LIBS=ON -DYAML_CPP_BUILD_TESTS=OFF -DYAML_CPP_BUILD_TOOLS=OFF -DYAML_CPP_BUILD_CONTRIB=OFF ..sudo make install
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                leosocy
                            
                    
                        
                            
                                    leosocy@gmail.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    On 11/22/2018 03:52，qymspace<notifications@github.com> wrote： 


First thanks for the library. I have been eagerly waiting for it.
Now to my issue, the compilation process is failing at sudo make install  step
[  8%] Linking CXX shared library librobust-palm-roi.so
/usr/bin/ld: /usr/local/lib/libyaml-cpp.a(exceptions.cpp.o): relocation R_X86_64_32S against `_ZTVN4YAML9ExceptionE' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libyaml-cpp.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
CMakeFiles/robust-palm-roi.dir/build.make:403: recipe for target 'librobust-palm-roi.so.0.1.0' failed
make[2]: *** [librobust-palm-roi.so.0.1.0] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/robust-palm-roi.dir/all' failed
make[1]: *** [CMakeFiles/robust-palm-roi.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2


—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by leosocy** [comment]
You should reinstall `yaml-cpp` as a shared library.  Step

1. mkdir build; cd build
1. cmake -DBUILD_SHARED_LIBS=ON -DYAML_CPP_BUILD_TESTS=OFF -DYAML_CPP_BUILD_TOOLS=OFF -DYAML_CPP_BUILD_CONTRIB=OFF ..
1. sudo make install

**Comment by qymspace** [comment]
Thanks. Works like a charm.

**Comment by qymspace** [comment]
But I got another issue when I run ```python run_sample.py```
```
Traceback (most recent call last):
  File "/home/qymspace/virtualenvironment/EDCC/local/lib/python3.5/site-packages/robust_palm_roi-0.1.0-py3.5.egg/rpr.py", line 28, in __init__
  File "/usr/lib/python3.5/ctypes/__init__.py", line 425, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.5/ctypes/__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: librobust-palm-roi.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_sample.py", line 19, in <module>
    chain = HandlerChain(ALGORITHM_CONFIG)
  File "/home/qymspace/virtualenvironment/EDCC/local/lib/python3.5/site-packages/robust_palm_roi-0.1.0-py3.5.egg/rpr.py", line 31, in __init__
OSError: Library [librobust-palm-roi] not found.
Please see https://github.com/Leosocy/RobustPalmRoi/blob/master/README.md#Installation
```

Trying to work through the installation instructions to see if I missed anything but everything looks okay.

**Comment by leosocy** [comment]
Please confirm that the installation has been successful and, if successful, you will see `librobust-palm -roi.so` in the `/usr/local/lib` directory.

**Comment by qymspace** [comment]
Yes, the file is available
```
 $ls /usr/local/lib/librobust-palm-roi.so
/usr/local/lib/librobust-palm-roi.so
```

**Comment by leosocy** [comment]
Create a file under `/etc/ld.so.conf.d/` directory, and write these line

```txt
/usr/local/lib
``` 

And then run `sudo ldconfig`.

**Comment by qymspace** [comment]
What should be the name of the file in ```/etc/ld.so.conf.d/```?

**Comment by qymspace** [comment]
Just named it ```robust.conf``` and it worked. Thanks

**Comment by leosocy** [comment]
Congratulation!
