### ISSUE TITLE
How to build in production

### ISSUE THREAD

**Issue by qymspace** [Leosocy/RobustPalmRoi#18]
First thank you for the beautiful program. I am using both https://github.com/Leosocy/EDCC-Palmprint-Recognition and this package and I am very sattisfied. 

My question is about how I would build this in production
I am thinking of using docker. 
Do I need to built it in every container of I can build in my computer and copy the binaries to docker.

**Comment by qymspace** [comment]
I was thinking I can start out with OpenCV docker image and install both RobustPalmRoi and EDCC-Palmprint-Recognition to create another image then use the resulting image us the base image for my application 
For example, because I am using NodeJS and Redis I would also need to install npm and node. 
I would then create a docker-compose file to connect the application with Redis database.

**Comment by leosocy** [comment]
Yes, that's a good idea. And you can refer to [EDCC Dockerfile](https://github.com/Leosocy/EDCC-Palmprint-Recognition/blob/master/Dockerfile.base).
Recently, I have been using micro services to integrate `EDCC` and `RobustPalmRoi`, but I am not good at front-end technology. If possible, we can build these projects together. I can provide API or RPC back-end services through flask or GRPC, and you can use NodeJS to provide front-end services. Then we can deploy these services on Kubernetes.
