### ISSUE TITLE
error running sudo make install in RobustPalmRoi/build

### ISSUE THREAD

**Issue by ajmakoni** [Leosocy/RobustPalmRoi#24]
Good day,
I am trying to use your ROI library. I have successfully installed yaml-cpp but getting error at `sudo make install` on RobustPalmRoi/build
Here is the snapshot of my error
![image](https://user-images.githubusercontent.com/516305/161413421-e7f6dcc0-a20b-48a3-a625-5f284e769a0b.png)
I am working on ubuntu 20.04, python 3.8.10
Any guidance on how to resolve it will be greatly appreciated

**Comment by leosocy** [comment]
What's the version of your OpenCV? Maybe you use OpenCV 4.x which not work well on this project, please try OpenCV - 3.4.

**Comment by ajmakoni** [comment]
Hi, yes it worked with opencv-3.4. Do you have any plans to support opencv4.x anytime soon?
